#!/usr/bin/env python3
"""Validate final v1.0.0 public release readiness."""
from pathlib import Path
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
required = [
    'README.md', 'RELEASE.md', 'ROADMAP.md', 'SUPPORT.md', 'PUBLICATION-CHECKLIST.md', 'CITATION.cff',
    'LICENSE', 'NOTICE.md', 'CHANGELOG.md', 'VERSION', 'repository-metadata.yaml',
    'docs/Final-Release-Checklist.md', 'docs/Repository-Launch-Guide.md', 'docs/Prompt-Inventory.md', 'docs/Configuration-Inventory.md',
    'docs/Public-Repository-Setup.md', 'docs/Profile-Family-Roadmap.md', 'docs/Profile-Authoring-Guide.md', 'docs/Schema-Configuration-Alignment.md', 'docs/Semantic-Validation-Guide.md', 'docs/Profile-Depth-Balance-Report.md', 'docs/Validation-Scope-and-Guarantees.md', 'docs/Final-Publication-Cut.md',
    '.github/workflows/validate.yml', '.github/ISSUE_TEMPLATE/bug_report.md', '.github/ISSUE_TEMPLATE/feature_request.md', '.github/ISSUE_TEMPLATE/config.yml', '.github/CODEOWNERS', '.github/PULL_REQUEST_TEMPLATE.md',
]
errors = [f'Missing release-readiness file: {r}' for r in required if not (ROOT / r).is_file()]
version = (ROOT / 'VERSION').read_text(encoding='utf-8').strip() if (ROOT / 'VERSION').exists() else ''
if version != '1.0.0':
    errors.append(f'Expected VERSION 1.0.0, found {version!r}')
for rel in ['README.md', 'RELEASE.md', 'ROADMAP.md', 'PUBLICATION-CHECKLIST.md', 'repository-metadata.yaml', 'CITATION.cff']:
    text = (ROOT / rel).read_text(encoding='utf-8') if (ROOT / rel).exists() else ''
    for token in ['DecisionComplete Prompt Pipeline', 'decision-complete-prompt-pipeline']:
        if token not in text:
            errors.append(f'Missing {token!r} in {rel}')
if 'Jayson-Furr/decision-complete-prompt-pipeline' not in (ROOT / 'CITATION.cff').read_text(encoding='utf-8'):
    errors.append('CITATION.cff does not reference Jayson-Furr/decision-complete-prompt-pipeline')
metadata_text = (ROOT / 'repository-metadata.yaml').read_text(encoding='utf-8') if (ROOT / 'repository-metadata.yaml').exists() else ''
if 'latest_batch: 13' not in metadata_text:
    errors.append('repository-metadata.yaml must identify latest_batch: 13 for the final publication cut')
if 'v1_0_0_final_publication_cut' not in metadata_text:
    errors.append('repository-metadata.yaml must identify v1_0_0_final_publication_cut')
for rel in ['README.md', 'PACKAGE-BUILD-STATUS.md', 'FINAL-PACKAGE-NOTES.md', 'docs/Batch-Build-Process.md']:
    text = (ROOT / rel).read_text(encoding='utf-8') if (ROOT / rel).exists() else ''
    if '/mnt/data' in text:
        errors.append(f'Public-facing sandbox path found in {rel}')
# validation-report.json is generated by tools/run-all-checks.py after validators run.
# Do not read a previous report here; run-all-checks is the source of truth for aggregate status.
if errors:
    print('Release readiness validation failed:')
    for error in errors:
        print('-', error)
    sys.exit(1)
print('Release readiness validation passed.')
